function stereo_camera_calibration_parameters_matlab(filepath, stereoParams)
    %extract parameters from stereoParams for easy access
    cameraMatrix1 = transpose(stereoParams.CameraParameters1.IntrinsicMatrix);
    cameraDistortionVector1 = [stereoParams.CameraParameters1.RadialDistortion(1),...
                               stereoParams.CameraParameters1.RadialDistortion(2),...
                               stereoParams.CameraParameters1.TangentialDistortion(1),...
                               stereoParams.CameraParameters1.TangentialDistortion(2),...
                               stereoParams.CameraParameters1.RadialDistortion(3)];
    cameraMatrix2 = transpose(stereoParams.CameraParameters2.IntrinsicMatrix);
    cameraDistortionVector2 = [stereoParams.CameraParameters2.RadialDistortion(1),...
                               stereoParams.CameraParameters2.RadialDistortion(2),...
                               stereoParams.CameraParameters2.TangentialDistortion(1),...
                               stereoParams.CameraParameters2.TangentialDistortion(2),...
                               stereoParams.CameraParameters2.RadialDistortion(3)];
    rotationMatrix = transpose(stereoParams.RotationOfCamera2);
    
    translationVector = stereoParams.TranslationOfCamera2;
    essentialMatrix = transpose(stereoParams.EssentialMatrix);
    fundamentalMatrix = transpose(stereoParams.FundamentalMatrix);
    
    %Output calibration params
    stereo_camera_parameters_export(filepath,...
                                    cameraMatrix1, cameraDistortionVector1,...
                                    cameraMatrix2, cameraDistortionVector2,...
                                    rotationMatrix, translationVector,...
                                    essentialMatrix, fundamentalMatrix);
end